### PR TITLE
Added connection from CoreImageBlock to MediaItem

### PR DESCRIPTION
**Pull request by Bryndille1701**
Hi.

Based on a personal problem, and to answer [this issue](https://github.com/pristas-peter/wp-graphql-gutenberg/issues/25), I propose this PR.

I'm of course welcome to modifications/advices. Note that this is my first ever PR to an open source project :)

### CODE REVIEW

**Comment by Bryndille1701** [comment]
@pristas-peter any updates on this ?

**Comment by sahandnayebaziz** [comment]
Hey @Bryndille1701, this PR looks great. I'm currently having an issue where images within galleries aren't giving me the right URL (I use offload-media to put images in S3) and I was surprised there was no way to get to the MediaItem from the `core/image` block. Looks like this what this PR adds, right? 

If so, I would love for this to be merged in. 

cc @pristas-peter

**Comment by sahandnayebaziz** [comment]
thank you @pristas-peter !

**Comment by sahandnayebaziz** [comment]
Hey @Bryndille1701, should this PR work out-of-the-box, if I just upload the code at this point to my WordPress as a plugin? I just uploaded a new zip from the latest `:develop` branch here, and I'm getting a 500 trying to load the built-in GraphQL IDE. If this is expected, no worries, but I wanted to flag it early in case it wasn't.


Screen Shot 2022-05-18 at 10 27 31 AM
Screen Shot 2022-05-18 at 10 27 01 AM

It says `0.3.11` here but it's actually the zip of this repo @ the latest :develop commit.

**Comment by Bryndille1701** [comment]
Hi ! I haven't merged the recent changes from :develop. I'll try this out and tell you about it. It should work without anything tho.

**Pull request merged**
